EVENT_LIST = ["FOMC", "NFP", "CPI", "PPI"]
INSTRUMENTS = {
    "EQUITY": ["SPY", "QQQ", "MSTR"],
    "CRYPTO": ["BTC-PERPETUAL", "ETH-PERPETUAL"],
}
MINUTES_BEFORE_RELEASE = 24 * 60
MINUTES_AFTER_RELEASE = 30
ADJ_MINUTES_AFTER_RELEASE = {"FOMC": 90}
YEARLY_TRADING_DAYS = 365.25
