EVENT_LIST = ["FOMC", "NFP", "CPI", "PPI"]
INSTRUMENTS = ["BTC-PERPETUAL", "ETH-PERPETUAL"]
CURRENCY_LIST = [instrument_name.replace("-PERPETUAL", "") for instrument_name in INSTRUMENTS]

MINUTES_BEFORE_RELEASE = 24 * 60
MINUTES_AFTER_RELEASE = 30
YEARLY_TRADING_DAYS = 365.25

EMA_RV_DAYS = 21
